"""API / MCP response schemas."""

from readdocsserver.schemas.domain import (
    ChunkSpan,
    EntityEdge,
    EntityHit,
    EntityXrefCandidate,
    SearchHit,
    SymbolInfo,
    SymbolMaps,
)
from readdocsserver.schemas.mcp import (
    EntityDetail,
    EntityDetailResponse,
    EntityMethodListResponse,
    EntityNote,
    EntityParam,
    EntityResult,
    EntitySearchResponse,
    FetchMetadata,
    FetchResponse,
    IndexStats,
    IndexedSource,
    ListPagesResponse,
    ListedPage,
    LookupSymbolResponse,
    RelatedSymbolEdge,
    RelatedSymbolRef,
    RelatedSymbolsResponse,
    SearchResponse,
    SearchResult,
    SourceListResponse,
    SymbolGraphStatsResponse,
    SymbolLookupResult,
)

__all__ = [
    "ChunkSpan",
    "EntityEdge",
    "EntityHit",
    "EntityXrefCandidate",
    "SearchHit",
    "SymbolInfo",
    "SymbolMaps",
    "EntityDetail",
    "EntityDetailResponse",
    "EntityMethodListResponse",
    "EntityNote",
    "EntityParam",
    "EntityResult",
    "EntitySearchResponse",
    "FetchMetadata",
    "FetchResponse",
    "IndexStats",
    "IndexedSource",
    "ListPagesResponse",
    "ListedPage",
    "LookupSymbolResponse",
    "RelatedSymbolEdge",
    "RelatedSymbolRef",
    "RelatedSymbolsResponse",
    "SearchResponse",
    "SearchResult",
    "SourceListResponse",
    "SymbolGraphStatsResponse",
    "SymbolLookupResult",
]
